name: AI Integration Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/ai/**'
      - 'tests/ai/**'
      - 'run_tests.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ai/**'
      - 'tests/ai/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    
    - name: Run tests
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh all
    
    - name: Run tests with coverage
      run: ./run_tests.sh coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./test_reports/coverage.xml
        flags: ai-integration
        name: ai-coverage
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: test_reports/
        retention-days: 30